name: youtube_watcher
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0-100.2.beta

# Add regular dependencies here.
dependencies:
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.4.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
